package com.redhat.bpms.demo.fsi.onboarding.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import org.drools.persistence.jpa.marshaller.MappedVariable;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Client")
public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CLIENT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CLIENT_ID_SEQ", name = "CLIENT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Country")
   private java.lang.String country;

   @org.kie.api.definition.type.Label("Type")
   private java.lang.String type;

   @org.kie.api.definition.type.Label("Business Identifier Code (BIC) (ISO 9362)")
   private java.lang.String bic;

   @org.kie.api.definition.type.Label("Related Parties")
   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER, orphanRemoval = false)
   private java.util.List<com.redhat.bpms.demo.fsi.onboarding.model.RelatedParty> relatedParties;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("Address")
   private com.redhat.bpms.demo.fsi.onboarding.model.Address address;

   @org.kie.api.definition.type.Label("Phone Number")
   private java.lang.String phoneNumber;

   @org.kie.api.definition.type.Label(value = "Credit Score")
   private java.lang.Integer creditScore;

   public Client()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getBic()
   {
      return this.bic;
   }

   public void setBic(java.lang.String bic)
   {
      this.bic = bic;
   }

   public java.util.List<com.redhat.bpms.demo.fsi.onboarding.model.RelatedParty> getRelatedParties()
   {
      return this.relatedParties;
   }

   public void setRelatedParties(
         java.util.List<com.redhat.bpms.demo.fsi.onboarding.model.RelatedParty> relatedParties)
   {
      this.relatedParties = relatedParties;
   }

   public com.redhat.bpms.demo.fsi.onboarding.model.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(com.redhat.bpms.demo.fsi.onboarding.model.Address address)
   {
      this.address = address;
   }

   public java.lang.String getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public Client(
         java.lang.Long id,
         java.lang.String name,
         java.lang.String country,
         java.lang.String type,
         java.lang.String bic,
         java.util.List<com.redhat.bpms.demo.fsi.onboarding.model.RelatedParty> relatedParties,
         com.redhat.bpms.demo.fsi.onboarding.model.Address address,
         java.lang.String phoneNumber, java.lang.Integer creditScore)
   {
      this.id = id;
      this.name = name;
      this.country = country;
      this.type = type;
      this.bic = bic;
      this.relatedParties = relatedParties;
      this.address = address;
      this.phoneNumber = phoneNumber;
      this.creditScore = creditScore;
   }
   
   // Copied over from VariableEntity for now- can't build from Business Central
   @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
   @JoinColumn(name = "MAP_VAR_ID", nullable = true)
   private Set<MappedVariable> mappedVariables;

   public Set<MappedVariable> getMappedVariables() {
       return mappedVariables;
   }

   public void setMappedVariables(Set<MappedVariable> mappedVariables) {
       this.mappedVariables = mappedVariables;
   }

   public void addMappedVariables(MappedVariable mappedVariable) {
       if (this.mappedVariables == null) {
           this.mappedVariables = new HashSet<MappedVariable>();
       }
       this.mappedVariables.add(mappedVariable);
   }

   public void removeMappedVariables(MappedVariable mappedVariable) {
       if (this.mappedVariables == null) {
           return;
       }
       this.mappedVariables.remove(mappedVariable);
   }

   public MappedVariable findMappedVariables(MappedVariable mappedVariable) {
       if (this.mappedVariables == null) {
           return null;
       }

       MappedVariable found = null;

       for (MappedVariable variable : mappedVariables) {
           if (variable.equals(mappedVariable)) {
               found = variable;
               break;
           }
       }

       return found;
   }

}